#
#	Operating System Lab
#	    Lab4 (File System in Userspace)
#	    Copyright (C) data/name/email
#	    First Writing: date
#
#   Makefile
#       - debugging option required
#       - library must be includded ( -l ./include/)
#       - -D_FILE_OFFSET_BITS=64 -I/usr/include/fuse -lfuse -pthread -DFUSE_USE_VERSION option required
#
# This program is free software; you can redistribute it and/or modify it
# under the terms and conditions of the GNU General Public License,
# version 2, as published by the Free Software Foundation.
#
# This program is distributed in the hope it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
# more details.
#
